# Generated by Django 3.2.3 on 2021-06-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='', max_length=200)),
                ('c_email', models.EmailField(default='', max_length=200)),
                ('c_nos', models.PositiveBigIntegerField(default=0)),
                ('c_add', models.TextField(default='')),
                ('join_date', models.DateField(auto_now=True, null=True)),
                ('profile', models.ImageField(blank=True, default='', max_length='30', null=True, upload_to='Comp_profile/')),
                ('c_pass', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
