# Generated by Django 3.2.3 on 2021-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_comp_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_customers',
            name='cust_join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
